/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a222_skip1103_project;
import javax. swing.*;
import java.awt.*;
public class MillonareGame extends javax.swing.JFrame {

    /**
     * Creates new form MillonareGame
     */
    public MillonareGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        millonareQuestion = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        lifeline5050 = new javax.swing.JButton();
        lifelineAskTheAudience = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        correctInterface = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        hallOfFame = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        player = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        startPlay = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        falseInterface = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        lifeline50 = new javax.swing.JPanel();
        lifelineAskAudience = new javax.swing.JPanel();
        ruless = new javax.swing.JFrame();
        rules = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayRules = new javax.swing.JTextArea();
        menu = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PLAY = new javax.swing.JButton();
        RULES = new javax.swing.JButton();
        SCORE = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        millonareQuestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("NEXT");
        millonareQuestion.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        millonareQuestion.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 760, 150));

        jTextField2.setText("jTextField1");
        millonareQuestion.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 360, 70));

        jTextField3.setText("jTextField1");
        millonareQuestion.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 380, 70));

        jTextField4.setText("jTextField1");
        millonareQuestion.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 360, 70));

        jTextField5.setText("jTextField1");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        millonareQuestion.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 380, 70));

        lifeline5050.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lifeline5050.setText("50/50");
        millonareQuestion.add(lifeline5050, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lifelineAskTheAudience.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lifelineAskTheAudience.setText("ASK THE AUDIENCE");
        millonareQuestion.add(lifelineAskTheAudience, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/backgrounf.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        millonareQuestion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        correctInterface.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 255));
        jLabel2.setText("CORRECT!");
        correctInterface.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 260, 70));

        jLabel25.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 153));
        jLabel25.setText("You've Won");
        correctInterface.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 130, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        correctInterface.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("NEXT");
        correctInterface.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        correctInterface.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 590, 340));

        hallOfFame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/1.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        hallOfFame.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, 120));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/2.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        hallOfFame.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, 120));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/3.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        hallOfFame.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 80, 110));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel18.setText("3rd");
        hallOfFame.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 30, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel19.setText("2nd");
        hallOfFame.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 30, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel20.setText("1st");
        hallOfFame.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 30, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        hallOfFame.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 50));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        hallOfFame.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 50));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        hallOfFame.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 150, 50));

        jLabel21.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 153));
        jLabel21.setText("HALL");
        hallOfFame.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, -1));

        jLabel22.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("OF");
        hallOfFame.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 30));

        jLabel23.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 102, 255));
        jLabel23.setText("FAME");
        hallOfFame.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        hallOfFame.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 581, -1));

        player.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("ENTER YOUR NAME :");
        player.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));
        player.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 270, -1));

        startPlay.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        startPlay.setForeground(new java.awt.Color(153, 0, 255));
        startPlay.setText("START");
        player.add(startPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        player.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        falseInterface.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Javanese Text", 0, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 102, 255));
        jLabel28.setText("FALSE!");
        falseInterface.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 70));

        jLabel27.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 153));
        jLabel27.setText("Your Final Prize :");
        falseInterface.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        falseInterface.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("MENU");
        falseInterface.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        falseInterface.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        javax.swing.GroupLayout lifeline50Layout = new javax.swing.GroupLayout(lifeline50);
        lifeline50.setLayout(lifeline50Layout);
        lifeline50Layout.setHorizontalGroup(
            lifeline50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lifeline50Layout.setVerticalGroup(
            lifeline50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lifelineAskAudienceLayout = new javax.swing.GroupLayout(lifelineAskAudience);
        lifelineAskAudience.setLayout(lifelineAskAudienceLayout);
        lifelineAskAudienceLayout.setHorizontalGroup(
            lifelineAskAudienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lifelineAskAudienceLayout.setVerticalGroup(
            lifelineAskAudienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ruless.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayRules.setColumns(20);
        displayRules.setRows(5);
        jScrollPane1.setViewportView(displayRules);

        rules.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 430, 210));

        menu.setBackground(new java.awt.Color(153, 153, 255));
        menu.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        menu.setForeground(new java.awt.Color(51, 51, 255));
        menu.setText("MENU");
        rules.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 102, 153));
        jLabel31.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 36)); // NOI18N
        jLabel31.setText("RULES");
        rules.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        jLabel30.setText("jLabel30");
        rules.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLAY.setBackground(new java.awt.Color(204, 153, 255));
        PLAY.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        PLAY.setText("PLAY");
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        getContentPane().add(PLAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 70, -1));

        RULES.setBackground(new java.awt.Color(255, 204, 102));
        RULES.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        RULES.setText("RULES");
        RULES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RULESActionPerformed(evt);
            }
        });
        getContentPane().add(RULES, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        SCORE.setBackground(new java.awt.Color(204, 102, 255));
        SCORE.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        SCORE.setText("SCORE");
        SCORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCOREActionPerformed(evt);
            }
        });
        getContentPane().add(SCORE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 80, -1));

        EXIT.setBackground(new java.awt.Color(255, 255, 102));
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 204));
        jLabel7.setText("MILLIONARE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, -1));

        jLabel5.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("TO BE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, -1));

        jLabel6.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 204));
        jLabel6.setText("WANTS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, -1));

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("WHO ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Cloud purple.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/cloud orng.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 70, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Cloud purple.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/SUN.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 120));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Rainbow.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 130, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/Background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
         new Players().setVisible(true);
         dispose();
    }//GEN-LAST:event_PLAYActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void RULESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RULESActionPerformed
        
        new Rules().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_RULESActionPerformed

    private void SCOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCOREActionPerformed
        this.setVisible(false);
        HallOfFame lf = new HallOfFame();
        lf.setVisible(true);
    }//GEN-LAST:event_SCOREActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MillonareGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MillonareGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MillonareGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MillonareGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MillonareGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton PLAY;
    private javax.swing.JButton RULES;
    private javax.swing.JButton SCORE;
    private javax.swing.JPanel correctInterface;
    private javax.swing.JTextArea displayRules;
    private javax.swing.JPanel falseInterface;
    private javax.swing.JPanel hallOfFame;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel lifeline50;
    private javax.swing.JButton lifeline5050;
    private javax.swing.JPanel lifelineAskAudience;
    private javax.swing.JButton lifelineAskTheAudience;
    private javax.swing.JButton menu;
    private javax.swing.JPanel millonareQuestion;
    private javax.swing.JTextField name;
    private javax.swing.JPanel player;
    private javax.swing.JPanel rules;
    private javax.swing.JFrame ruless;
    private javax.swing.JButton startPlay;
    // End of variables declaration//GEN-END:variables
}
