/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a222_skip1103_project;


public class Rules extends javax.swing.JFrame {

    /**
     * Creates new form Rules
     */
    public Rules() {
        initComponents();
        displayRules.append("\nAfter viewing a question, the contestant can leave the game with the\n" +
                           "money already won rather than attempting an answer.");
        displayRules.append("\n");
        displayRules.append("\nEach question will be displayed together with 4 different possible answers which only\n" +
                           "one has to be correct.");
        displayRules.append("\n");
        displayRules.append("\nThere is no time limit to answer a question");
        displayRules.append("");
        displayRules.append("\nIf the contestant answers a question incorrectly, then all of their winnings are lost,\n" +
                           "except that the RM1,000 and RM100,000 prizes are guaranteed: if a player gets a\n" +
                           "question wrong above these levels, then the prize drops to the previous\n" +
                           "guaranteed prize.");
        displayRules.append("\n");
        displayRules.append("\nThe prizes are not cumulative. For example, answering the RM500 question gives\n" +
                           "the contestant RM500, not the previous RM100 plus RM500 (i.e. RM600).");
        displayRules.append("\n");
        displayRules.append("\nThe game ends when the contestant answers a question incorrectly, decides not\n" +
                           "to answer a question, or answers all questions correctly.");
        displayRules.append("\n");
        displayRules.append("\nLifelines: The system will provide the possibility of choosing “lifelines”: If at any point\n" +
                           "the contestant is unsure of the answer to a question, he or she can use one or more\n" +
                           "“lifelines’ which provide some form of assistance. After using a lifeline, the contestant\n" +
                           "can either answer the question, use another lifeline, or walk away and keep the\n" +
                           "money. Each lifeline can only be used once per game.\n"); 
        displayRules.append("\n");
        displayRules.append("a) 50/50: The contestant asks the system to randomly eliminate two of the incorrect\n" +
                           "answer choices, leaving the contestant with a choice between the correct answer\n" +
                           "and one incorrect one.\n");
        displayRules.append("\n");
        displayRules.append("b) Ask the Audience: The contestant asks the system to simulate the audience's\n" +
                           "opinion on correct answers. The result shall reflect a predefined outcome with a\n" +
                           "distribution of answers over all four answer choices.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayRules = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBtn.setBackground(new java.awt.Color(153, 153, 255));
        menuBtn.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(51, 51, 255));
        menuBtn.setText("MENU");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });
        getContentPane().add(menuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 102, 153));
        jLabel31.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 36)); // NOI18N
        jLabel31.setText("RULES");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        displayRules.setColumns(20);
        displayRules.setRows(5);
        jScrollPane2.setViewportView(displayRules);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 580, 300));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a222_skip1103_project/backgrounf.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        new MillonareGame().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayRules;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menuBtn;
    // End of variables declaration//GEN-END:variables
}
